#!/usr/bin/ruby

require 'inifile'

if 1 != ARGV.length
  puts "Usage: ./jenkins_tests x.x.x.x"
  puts "where x.x.x.x is the IP of the machine under test"
  exit
end

def puts! args, label=""
  puts "+++ +++ #{label}"
  puts args.inspect
end

client_ip = ARGV[0]
puts! client_ip, "The machine being tested is"

` sudo apt-get install python-virtualenv -y &&
  ./bootstrap &&
  patch virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py < patches/20150208.bad_status_line.patch &&
  patch virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py < patches/20150210.bad_status_line.patch `

` cp local.conf.example local.conf `
` sed -i 's/<machine-being-tested>/#{client_ip}/' local.conf `

## See /opt/nedge/src/nmf/lib/s3/bin/auditserv_set_flush_interval
# flush_interval = 1
# file = IniFile.load '/opt/nedge/etc/ccow/auditd.ini'
# ` cp /opt/nedge/etc/ccow/auditd.ini /opt/nedge/etc/ccow/auditd.ini-bk `
# file['statsite']['flush_interval'] = flush_interval
# file.write()
# if File.directory?( '/opt/nedge/nmf/etc' )
#   ` /opt/nedge/nmf/nefadm restart auditserv `
# else
#   ` /opt/nedge/src/nmf/nefadm restart auditserv `
# end


` S3TEST_CONF=local.conf ./virtualenv/bin/nosetests s3tests.functional.test_s3 &&
  S3TEST_CONF=local.conf ./virtualenv/bin/nosetests s3tests.functional.test_headers `
exit_status = $?.exitstatus
puts! exit_status, "exit status of Swift S3 Tests"

## See /opt/nedge/src/nmf/lib/s3/bin/auditserv_restore_settings
# ` cp /opt/nedge/etc/ccow/auditd.ini-bk /opt/nedge/etc/ccow/auditd.ini `
# if File.directory?( '/opt/nedge/nmf/etc' )
#   ` /opt/nedge/nmf/nefadm restart auditserv `
# else
#   ` /opt/nedge/src/nmf/nefadm restart auditserv `
# end


exit exit_status
