#!/usr/bin/ruby

require 'httparty'
require 'json'

SLEEP_INTERVAL = 6

if 1 != ARGV.length
  puts "Usage: ./jenkins_tests x.x.x.x"
  puts "where x.x.x.x is the IP of the machine under test"
  exit
end

def puts! args, label=""
  puts "+++ +++ #{label}"
  puts args.inspect
end

client_ip = ARGV[0]
puts! client_ip, "The machine being tested is"

` sudo apt-get install python-virtualenv -y &&
  ./bootstrap &&
  pip install requests[security] &&
  patch virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py < patches/20150208.bad_status_line.patch &&
  patch virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py < patches/20150210.bad_status_line.patch `

` cp local.conf.example local.conf `
` sed -i 's/<machine-being-tested>/#{client_ip}/' local.conf `

# store old flush interval
result = HTTParty.get( "http://#{client_ip}:8080/sysconfig/auditd/flushInterval", :headers => { 'authorization' => "Basic YWRtaW46bmV4ZW50YQ==" } )
@old_flush_interval = JSON.parse( result.body )['response']['value']
puts! @old_flush_interval, "Old flush interval is"
# set flush interval to 1
HTTParty.put "http://#{client_ip}:8080/sysconfig/ccowgw/flushInterval", :headers => { 'authorization' => "Basic YWRtaW46bmV4ZW50YQ==" }, :body => { 'value' => 1 }
sleep SLEEP_INTERVAL

` S3TEST_CONF=local.conf ./virtualenv/bin/nosetests s3tests.functional.test_s3 &&
  S3TEST_CONF=local.conf ./virtualenv/bin/nosetests s3tests.functional.test_headers `
exit_status = $?.exitstatus
puts! exit_status, "exit status of Swift S3 Tests"

# reset flush interval
HTTParty.put "http://#{client_ip}:8080/sysconfig/auditd/flushInterval", :headers => { 'authorization' => "Basic YWRtaW46bmV4ZW50YQ==" }, :body => { 'value' => @old_flush_interval }
sleep SLEEP_INTERVAL

exit exit_status
